### ISSUE TITLE
VAR typo

### ISSUE THREAD

**Issue by pascalandy** [raspberrycoulis/docker-ghost-letsencrypt-nginx#1]
Here, I think we should see [BLOG TWO]

https://github.com/raspberrycoulis/docker-ghost-letsencrypt-nginx/blob/dcd2f06293aca20810b5a165118192c9b1204e25/default#L54

**Comment by raspberrycoulis** [comment]
@pascalandy nope. The SSL certificate is created to include additional domains, so you use the `[BLOG ONE]` certificate in both blogs because the SSL certificate is valid for both blogs.

**Comment by pascalandy** [comment]
thanks
